### ISSUE TITLE
How to find the north, south, east and west coordinates of each city 

### ISSUE THREAD

**Issue by Kellokes** [henrydatei/upland.me-api#1]
Hi  @henrydatei, how are you?

I would like to know how do you get the coordinates (north, south, east and west) used on the API 
https://api.upland.me/properties/list-view?

Tks to much.

**Comment by henrydatei** [comment]
I'm fine thx.

I zoomed out to the maximum and then went north (south, east, west). After that I looked at the network requests in my browser and when the map is loaded, the coordinates were send to the server. I hope that helps.

**Comment by Kellokes** [comment]
Nice Henry!! Tks a lot!

By the way, all the work you've done so far is very cool.

Do you intend to go deeper? Upland is improve a lot and I believe the game has a future.

Do you play yet?

**Comment by henrydatei** [comment]
As I'm not playing upland at the moment, there are no plans for going any further. I played upland the time I created this repo but back then after signing up your account was like a guest account and you had to renew your visa every 7 days. I had a script running that did this for me but something gone wrong (changed the api/my script was not right/the server crashed/...) and then my account got deleted.

But since this repo got some attention I might be starting to play upland again and then I will do some work here.
